# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup-git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - run: npm run build --if-present
    - run: npm version patch # This are just snippets, no breaking changes or stuff like that to worry about
    - run: git commit -m "Automatic build" -a
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tags: true
